name: Build Flutter

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      #- uses: actions/checkout@v3
      #  with:
      #    repository: flutter/engine

      - name: Import SSH Key
        uses: shimataro/ssh-key-action@v2.5.0
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: unnecessary

      - name: Setup Ninja
        uses: ashutoshvarma/setup-ninja@master

      - name: Initialize depot_tools
        run: |
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git --depth 1

      - name: Configure gclient
        run: |
          mkdir engine
          cat <<- EOF > engine/.gclient
          solutions = [
            {
              "managed": False,
              "name": "src/flutter",
              "url": "git@github.com:Iyxan23/flutter-engine.git",
              "custom_deps": {},
              "deps_file": "DEPS",
              "safesync_url": "",
            },
          ]
          EOF

      - name: Update dependencies
        run: |
          cd engine
          ../depot_tools/gclient sync

      - name: Install deps
        run: |
          sudo engine/src/build/install-build-deps.sh | yes
          sudo engine/src/flutter/build/install-build-deps-linux-desktop.sh | yes
    
      - name: Generate build files
        run: engine/flutter/tools/gn
      
      - name: Build
        run: ninja -C out

      - name: Archive and upload build artifacts
        uses: RockLobster/archiving-upload-artifact@v0.2.1
        with:
          name: out-files
          directory: out
